- name: Enable/Install AD Domain Services feature
  win_feature:
   name: AD-Domain-Services
   include_management_tools: yes
   include_sub_features: yes

- name: Setup AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_controller

- name: Reboot if required after AD controller setup
  win_reboot:
  when: ad_controller.reboot_required

- name: List Domain Controllers in domain
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list

- debug:
   var: domain_list